// packages/react/packages/components/Waterfall.tsx
import "./waterfall.css";
import type { ICardItem, IPosItem, IRenderItem, IWaterfallProps } from "./type";
import { throttle, debounce } from "./tools";
import { useEffect, useRef, useState } from "react";
export default function Waterfall({
  gap = 16,
  pageSize = 50,
  showLoading = true,
  columnNum,
  request,
  children,
  loadingSlot,
  backTopSlot,
  onCardClick,
  requestError,
}: IWaterfallProps) {
  const waterfallContainerRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const slotRefs = useRef<{ [key: number]: HTMLDivElement }>({});

  const columnWidth = useRef(0);
  const page = useRef(1);
  const screenOffset = useRef(0);
  const dataList = useRef<ICardItem[]>([]);

  const positionList = useRef<IPosItem[]>([]);
  const domDataList = useRef<IRenderItem[]>([]);
  const isLoadNextPage = useRef(false);
  const isShowToTop = useRef(false);
  const hasNextPage = useRef(true);
  const lastOffsetWidth = useRef(0);
  const [renderList, setRenderList] = useState<IRenderItem[]>([]);
  const timer = useRef<number | NodeJS.Timeout>(0);
  //初始化数据
  useEffect(() => {
    init();
  }, []);

  //监听滚动
  useEffect(() => {
    const waterfallContainerEle = waterfallContainerRef.current;
    waterfallContainerEle?.addEventListener("scroll", () => {
      handleScroll();
    });
    return () => {
      waterfallContainerEle?.removeEventListener("scroll", handleScroll);
    };
  }, []);
  //监听容器尺寸变化
  useEffect(() => {
    const resizeObserver = new ResizeObserver(() => {
      handleResize();
    });
    if (waterfallContainerRef.current) {
      resizeObserver.observe(waterfallContainerRef.current);
    }
    return () => {
      if (waterfallContainerRef.current) {
        resizeObserver.unobserve(waterfallContainerRef.current);
      }
    };
  }, [columnNum]);
  const init = async () => {
    screenOffset.current = waterfallContainerRef.current!.offsetHeight / 2;
    lastOffsetWidth.current = waterfallContainerRef.current!.offsetWidth;
    computeColumnWidth();
    initPositionList();
    computeDomData(await getList(), 0);
  };

  const handleScroll = throttle(async () => {
    const scrollTop = waterfallContainerRef.current!.scrollTop;
    isShowToTop.current = scrollTop >= window.innerHeight;

    updatePos();
    if (isLoadNextPage.current || !hasNextPage.current) {
      return false;
    }
    if (
      waterfallContainerRef.current!.scrollTop + waterfallContainerRef.current!.offsetHeight >=
      waterfallContainerRef.current!.scrollHeight * 0.85
    ) {
      isLoadNextPage.current = true;
      page.current++;
      const nextList = await getList();
      isLoadNextPage.current = false;
      const startIdx = (page.current - 1) * pageSize;
      computeDomData(nextList, startIdx);
    }
  });
  //容器尺寸变化
  const handleResize = debounce(function () {
    resizeFn();
  }, 150);
  const resizeFn = () => {
    computeColumnWidth();
    lastOffsetWidth.current = waterfallContainerRef.current!.offsetWidth;
    initPositionList();
    computeDomData(dataList.current, 0, true);
  };
  const initPositionList = () => {
    positionList.current = [];
    for (let i = 0; i < columnNum; i++) {
      positionList.current.push({
        columnIdx: i + 1, //第几列
        columnHeight: 0, //对应高
      });
    }
  };
  //计算每一列宽度
  const computeColumnWidth = () => {
    const allGapLength = (columnNum - 1) * gap;
    columnWidth.current = (containerRef.current!.offsetWidth - allGapLength) / columnNum;
  };
  const computeDomData = (list: ICardItem[], startIdx: number = 0, isReSize = false) => {
    const length = list.length;
    for (let i = 0; i < length; i++) {
      const item = list[i];
      const idx = i + startIdx;
      const imageHeight = (item.height * columnWidth.current) / item.width;
      const param = {
        ...item,
        idx,
        columnIdx: 0,
        imageHeight,
        height: imageHeight,
        width: columnWidth.current,
        top: 0,
        left: 0,
        show: true,
        url: item.url || "",
        style: {
          width: columnWidth.current + "px",
          height: (item.height * columnWidth.current) / item.width + "px",
        },
      };
      if (isReSize) {
        domDataList.current[i] = param;
      } else {
        domDataList.current.push(param);
      }
    }
    setRenderList(domDataList.current.filter((item) => item.show));
    timer.current = setTimeout(() => {
      setCardPos(startIdx);
      clearTimeout(timer.current);
    }, 0);
  };
  const setCardPos = (startIdx: number) => {
    const length = domDataList.current.length;
    const end = startIdx === 0 ? length : startIdx + pageSize;
    const endIdx = end <= length ? end : length;
    for (let i = startIdx; i < endIdx; i++) {
      const domItem = domDataList.current[i];
      const { imageHeight, width, idx } = domItem;
      const param: ICardItem = {
        ...domItem,
      };
      const footer_height = slotRefs.current[idx].offsetHeight; //获取底部高度
      const height = imageHeight + footer_height;
      positionList.current.sort((a, b) => a.columnHeight - b.columnHeight);
      const minColumn = positionList.current[0];
      const { columnIdx, columnHeight } = minColumn;
      const top = columnHeight;
      const left = (columnIdx - 1) * (columnWidth.current + gap);
      param.columnIdx = columnIdx;
      param.top = top;
      param.left = left;
      param.height = height;
      param.style = {
        width: width + "px",
        height: height + "px",
        transform: `translate(${left}px,${top}px)`,
      };
      param.show = checkIsRender(param);
      positionList.current[0].columnHeight += height + gap;
      domDataList.current[i] = { ...domItem, ...param };
    }
    setRenderList(domDataList.current.filter((item) => item.show));
    setContainerHeight();
  };
  const updatePos = () => {
    domDataList.current.forEach((item, index) => {
      domDataList.current[index].show = checkIsRender(item);
    });
    setRenderList(domDataList.current.filter((item) => item.show));
  };
  const setContainerHeight = () => {
    const loadingHeight = showLoading ? 32 : 0;
    positionList.current.sort((a, b) => a.columnHeight - b.columnHeight);
    containerRef.current!.style.height =
      positionList.current[positionList.current.length - 1].columnHeight + loadingHeight + "px";
  };
  const checkIsRender = (params: ICardItem) => {
    const { top, height } = params;
    const y = top + height;
    const topLine = waterfallContainerRef.current!.scrollTop - screenOffset.current;
    const bottomLine =
      waterfallContainerRef.current!.scrollTop + waterfallContainerRef.current!.offsetHeight + screenOffset.current;
    const overTopLine = y < topLine;
    const underBottomLine = top > bottomLine;
    return !overTopLine && !underBottomLine;
  };
  const getList = async () => {
    try {
      const nextList = await request(page.current, pageSize);
      hasNextPage.current = !!nextList.length && nextList.length === pageSize;
      dataList.current = page.current === 1 ? nextList : dataList.current.concat(nextList);
      return nextList;
    } catch (error) {
      requestError && requestError(error);
    }
  };
  const scrollToTop = () => {
    waterfallContainerRef.current!.scrollTo({
      left: 0,
      top: 0,
      behavior: "smooth",
    });
  };
  return (
    <div ref={waterfallContainerRef} className="hm_waterfall-container">
      <div ref={containerRef} className="hm_container">
        {renderList.map((item) => {
          return (
            <div
              className="hm_waterfall-item"
              key={item.idx}
              style={item.style}
              onClick={() => onCardClick && onCardClick(item)}
            >
              <div
                className="hm_waterfall-item-main"
                style={{
                  height: item.imageHeight,
                  backgroundImage: "url(" + item.url + ")",
                  backgroundSize: "100% 100%",
                }}
              ></div>
              <div
                className="hm_waterfall-footer"
                ref={(el: HTMLDivElement) => (slotRefs.current[item.idx] = el)}
                style={{ width: item.width + "px" }}
              >
                {children?.(item)}
              </div>
            </div>
          );
        })}
        {showLoading && isLoadNextPage.current ? (
          <div className="hm_waterfall-loading">{loadingSlot ? loadingSlot : " 加载中..."}</div>
        ) : null}
        {isShowToTop.current ? (
          <div className="hm_waterfall-back-top" onClick={scrollToTop}>
            {backTopSlot}
          </div>
        ) : null}
      </div>
    </div>
  );
}

// packages/vue/packages/components/Waterfall.vue
<template>
  <div ref="waterfall-container" class="hm_waterfall-container" @scroll="handleScroll">
    <div ref="container" class="hm_container">
      <div
        v-for="item in renderList"
        :ref="item.ref"
        :key="item.idx"
        class="hm_waterfall-item"
        :style="item.style"
        @click="cardClick(item)"
      >
        <div
          class="hm_waterfall-item-main"
          :style="{
            height: item.imageHeight + 'px',
            backgroundImage: 'url(' + item.url + ')',
            backgroundSize: '100% 100%'
          }"
        />
        <div :ref="'item_' + item.idx" :style="{ width: item.width + 'px' }">
          <slot :item="item" />
        </div>
      </div>
      <div v-if="showLoading && isLoadNextPage" ref="loading" class="hm_waterfall-loading">
        <slot name="loadingSlot">加载中...</slot>
      </div>
      <div v-if="isShowToTop" class="hm_waterfall-back-top">
        <slot name="backTopSlot" />
      </div>
    </div>
  </div>
</template>
<script>
import { throttle, debounce } from './tools'

export default {
  name: 'HmWaterfall',
  props: {
    pageSize: {
      type: Number,
      default: 50
    },
    request: {
      type: Function,
      default: () => {}
    },
    //间隔宽度
    gap: {
      type: Number,
      default: 16
    },
    //是否显示加载图标
    showLoading: {
      type: Boolean,
      default: true
    },
    columnNum: {
      type: Number,
      default: 2
    }
  },
  data() {
    return {
      waterfallcontainerRef: null,
      containerRef: null,
      columnWidth: 0, //每列宽度
      page: 1,
      list: [],
      positionList: [], //列数据
      domDataList: [],
      screenOffset: 0,
      isLoadNextPage: false,
      isShowToTop: false,
      hasNextPage: true,
      resizeObserver: null,
      lastOffsetWidth: 0
    }
  },
  computed: {
    renderList() {
      const list = this.domDataList.filter((item) => item.show)
      return list
    }
  },
  watch: {
    columnNum() {
      this.handleResize()
    }
  },
  beforeDestroy() {
    this.resizeObserver.disconnect()
  },
  async mounted() {
    this.waterfallcontainerRef = this.$refs['waterfall-container']
    this.containerRef = this.$refs['container']
    this.screenOffset = this.waterfallcontainerRef.offsetHeight / 2
    this.computeColumnWidth()
    this.initPositionList()
    this.computeDomData(await this.getList(), 0)
    this.lastOffsetWidth = this.waterfallcontainerRef.offsetWidth
    this.resizeObserver = new ResizeObserver((entries) => {
      //避免初始化就运行问题
      if (entries[0].borderBoxSize[0].inlineSize !== this.lastOffsetWidth) {
        this.handleResize()
      }
    })
    this.resizeObserver.observe(this.waterfallcontainerRef)
  },

  methods: {
    handleResize: debounce(function () {
      this.resizeFn()
    }, 150),
    resizeFn() {
      this.computeColumnWidth()
      this.lastOffsetWidth = this.waterfallcontainerRef.offsetWidth
      this.initPositionList()
      this.computeDomData(this.list, 0, true)
    },
    handleScroll: throttle(async function () {
      const scrollTop = this.waterfallcontainerRef.scrollTop
      this.isShowToTop = scrollTop >= window.innerHeight
      this.updatePos()
      if (this.isLoadNextPage || !this.hasNextPage) {
        return false
      }
      if (
        this.waterfallcontainerRef.scrollTop + this.waterfallcontainerRef.offsetHeight >=
        this.waterfallcontainerRef.scrollHeight * 0.85
      ) {
        this.isLoadNextPage = true
        this.page++
        const list = await this.getList()
        this.isLoadNextPage = false
        const startIdx = (this.page - 1) * this.pageSize
        this.computeDomData(list, startIdx)
      }
    }),
    //计算每一列宽度
    computeColumnWidth() {
      const allGapLength = (this.columnNum - 1) * this.gap
      this.columnWidth = (this.containerRef.offsetWidth - allGapLength) / this.columnNum
      return this.columnWidth
    },
    //重置每列数据
    initPositionList() {
      this.positionList = []
      for (let i = 0; i < this.columnNum; i++) {
        this.positionList.push({
          columnIdx: i + 1, //第几列
          columnHeight: 0 //对应高
        })
      }
    },
    computeDomData(list, startIdx = 0, isReSize = false) {
      const length = list.length
      for (let i = 0; i < length; i++) {
        const item = list[i]
        const idx = i + startIdx
        const imageHeight = (item.height * this.columnWidth) / item.width
        const param = {
          ...item,
          idx,
          columnIdx: 0,
          ref: 'item_' + idx,
          imageHeight,
          height: imageHeight,
          width: this.columnWidth,
          top: 0,
          left: 0,
          show: true,
          style: {
            width: this.columnWidth + 'px',
            height: imageHeight + 'px'
          }
        }

        if (isReSize) {
          this.$set(this.domDataList, i, { ...param })
        } else {
          this.domDataList.push(param)
        }
      }
      this.$nextTick(() => {
        this.setCardPos(startIdx)
      })
    },
    setCardPos(startIdx) {
      const length = this.domDataList.length
      const end = startIdx === 0 ? length : startIdx + this.pageSize
      const endIdx = end <= length ? end : length
      for (let i = startIdx; i < endIdx; i++) {
        const domItem = this.domDataList[i]
        const { idx, imageHeight, width } = domItem
        const param = {
          ...domItem
        }
        const footer_slot = this.$refs['item_' + idx]
        const footer_height = footer_slot ? footer_slot[0].offsetHeight : 0
        const height = imageHeight + footer_height
        this.positionList.sort((a, b) => a.columnHeight - b.columnHeight)
        const minColumn = this.positionList[0]
        const { columnIdx, columnHeight } = minColumn
        const top = columnHeight
        const left = (columnIdx - 1) * (this.columnWidth + this.gap)
        param.columnIdx = columnIdx
        param.top = top
        param.left = left
        param.height = height
        param.style = {
          width: width + 'px',
          height: height + 'px',
          transform: `translate(${left}px,${top}px)`
        }
        param.show = this.checkIsRender(param)
        this.positionList[0].columnHeight += height + this.gap
        this.$set(this.domDataList, i, { ...domItem, ...param })
      }
      this.setContainerHeight()
    },
    updatePos() {
      this.domDataList.forEach((item, index) => {
        this.domDataList[index].show = this.checkIsRender(item)
      })
    },
    checkIsRender(params) {
      const { top, height } = params
      const y = top + height
      const topLine = this.waterfallcontainerRef.scrollTop - this.screenOffset
      const bottomLine =
        this.waterfallcontainerRef.scrollTop + this.waterfallcontainerRef.offsetHeight + this.screenOffset
      const overTopLine = y < topLine
      const underBottomLine = top > bottomLine
      return !overTopLine && !underBottomLine
    },
    setContainerHeight() {
      const loadingHeight = this.showLoading ? 32 : 0
      this.positionList.sort((a, b) => a.columnHeight - b.columnHeight)
      this.containerRef.style.height =
        this.positionList[this.positionList.length - 1].columnHeight + loadingHeight + 'px'
    },
    getColumnNum(boxWidth) {
      if (boxWidth > 1600) {
        return 5
      } else if (boxWidth > 1200) {
        return 4
      } else if (boxWidth >= 768) {
        return 3
      } else {
        return 2
      }
    },
    async getList() {
      try {
        const nextList = await this.request(this.page, this.pageSize)
        this.hasNextPage = !!nextList.length && nextList.length === this.pageSize
        this.list = this.page === 1 ? nextList : this.list.concat(nextList)
        return nextList
      } catch (error) {
        this.$emit('on-fail-request')
      }
    },
    cardClick(item) {
      this.$emit('on-card-click', item)
    }
  }
}
</script>
<style scoped>
@import './waterfall.css';
</style>
